app:
  image: opinioapp/ember-cli:2.14.0
  volumes:
    - $SSH_AUTH_SOCK:/ssh-agent
    - .:/myapp
  environment:
    - SSH_AUTH_SOCK=/ssh-agent
  command: ember server
  ports:
      - "4200:4200"
      - "49153:49153"
      - "3000:3000"
